/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>  
          (url.origin === self.location.origin && url.pathname.endsWith('.jpg') ||
          url.origin === self.location.origin && url.pathname.endsWith('.png')), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.

const urlsToCache = ["/", 
                    "/images/arrow.png", 
                    "/images/brasaoNE.webp",
                    "/images/brasaoMB.webp",
                    "/images/comp/ne-aud-1.jpg",
                    "/images/comp/ne-aud-2.jpg",
                    "/images/comp/ne-aud-3.jpg",
                    "/images/comp/ne-aud-4.jpg",
                    "/images/comp/ne-aud-5.jpg",
                    "/images/comp/ne-beg-1.jpg",
                    "/images/comp/ne-cam-1.jpg",
                    "/images/comp/ne-cir-1.jpg",
                    "/images/comp/ne-cir-2.jpg",
                    "/images/comp/ne-cmdt-1.jpg",
                    "/images/comp/ne-cmdt-2.jpg",
                    "/images/comp/ne-conv-1.jpg",
                    "/images/comp/ne-crd-1.jpg",
                    "/images/comp/ne-crd-10.jpg",
                    "/images/comp/ne-crd-11.jpg",
                    "/images/comp/ne-crd-12.jpg",
                    "/images/comp/ne-crd-13.jpg",
                    "/images/comp/ne-crd-2.jpg",
                    "/images/comp/ne-crd-3.jpg",
                    "/images/comp/ne-crd-4.jpg",
                    "/images/comp/ne-crd-5.jpg",
                    "/images/comp/ne-crd-6.jpg",
                    "/images/comp/ne-crd-7.jpg",
                    "/images/comp/ne-crd-8.jpg",
                    "/images/comp/ne-crd-9.jpg",
                    "/images/comp/ne-dent-1.jpg",
                    "/images/comp/ne-gm-1.jpg",
                    "/images/comp/ne-gm-2.jpg",
                    "/images/comp/ne-gm-3.jpg",
                    "/images/comp/ne-gm-4.jpg",
                    "/images/comp/ne-gm-5.jpg",
                    "/images/comp/ne-gm-6.jpg",
                    "/images/comp/ne-gm-7.jpg",
                    "/images/comp/ne-nav-1.jpg",
                    "/images/comp/ne-nav-2.jpg",
                    "/images/comp/ne-nav-3.jpg",
                    "/images/comp/ne-pass-1.jpg",
                    "/images/comp/ne-pass-2.jpg",
                    "/images/comp/ne-pass-3.jpg",
                    "/images/comp/ne-pass-4.jpg",
                    "/images/comp/ne-prd-1.jpg",
                    "/images/comp/ne-prd-2.jpg",
                    "/images/comp/ne-prd-3.jpg",
                    "/images/comp/ne-prd-4.jpg",
                    "/images/comp/ne-prd-5.jpg",
                    "/images/comp/ne-sala-1.jpg",
                    "/images/comp/ne-sstt-1.jpg",
                    "/images/comp/ne-sstt-2.jpg",
                    "/images/comp/ne-sstt-3.jpg",
                    "/images/comp/ne-sstt-4.jpg"
                  ];
self.addEventListener("install", event => {
  event.waitUntil(
     caches.open("images")
     .then(cache => {
        return cache.addAll(urlsToCache);
     })
  );
});